#include "game_basics.h"
/** VALUES FOR LAUNCHER */
#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

/** VALUES FOR GAME */
#define MAP_SMALL 16
#define MAP_MEDIUM 24
#define MAP_LARGE 32
#define MAP_SM_GRID MAP_SMALL * MAP_SMALL
#define MAP_MD_GRID MAP_MEDIUM * MAP_MEDIUM
#define MAP_LG_GRID MAP_LARGE * MAP_LARGE
#define CELL_DIM 38
#define PLAYER_HEIGHT 32
#define PLAYER_WIDTH 32
#define PLAYER_1_SPEED 256
#define PLAYER_2_SPEED 256
#define PLAYER_1_SPAWN_X 114
#define PLAYER_1_SPAWN_Y 152
#define PLAYER_2_SPAWN_X 114
#define PLAYER_2_SPAWN_Y 190
#define PLAYER_1_RCOLOR 000
#define PLAYER_1_GCOLOR 000
#define PLAYER_1_BCOLOR 255
#define PLAYER_2_RCOLOR 255
#define PLAYER_2_GCOLOR 000
#define PLAYER_2_BCOLOR 000
#define PLAYER_1_ID 0x001
#define PLAYER_2_ID 0x002


