#include "game_basics.h"

#define W BLOCK_MASK_UNWALKABLE |+ BLOCK_LIMIT
#define D BLOCK_MASK_UNWALKABLE |+ BLOCK_WALL
#define P1 BLOCK_MASK_UNWALKABLE |+ BLOCK_PLAYER1WALL
#define P2 BLOCK_MASK_UNWALKABLE |+ BLOCK_PLAYER2WALL